name: .NET Application Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./backend
    - name: Build
      run: dotnet build ./backend --no-restore
    - name: Test
      run: dotnet test ./backend --no-build --verbosity normal
